name: test-action
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10]

    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v3

      - name: test1
        id: time1
        uses: juan-fgr/time-action@v1.0

      - name: test1-output
        env:
          TIME: "${{ steps.time1.outputs.time }}"
        run: |
          echo $TIME
      - name: test2
        id: time2
        uses: juan-fgr/time-action@v1.0
        with:
          timeZone: 8
          format: 'YYYY-MM-DD_HH:mm:ss'

      - name: test2-output
        env:
          TIME: "${{ steps.time2.outputs.time }}"
        run: |
          echo $TIME